name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

env:
  FORCE_COLOR: "1"

jobs:
  check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Odin
        run: |
          git clone https://github.com/odin-lang/Odin.git --depth 1 --single-branch --branch=master
          cd Odin
          make
          echo "$(pwd)" >> "$GITHUB_PATH"
          ./odin report
      - name: Run test
        run: ./odin test .
        timeout-minutes: 1
      # - name: Odin check
      #   if: success() || failure()
        # run: odin check . -vet --strict-style
